package com.company;

public class Main {


    public static void main(String[] args) {
        countingDnaNucleotides("CCCACCATACTACCATCTCCGGCGGCTTAATCACAGATTATAGTAACCCTAACTTTTATTGGTGTCCGCGAACCCGACATCAGACATCAACTCGACCGGAAACACAGACTCGCGTAAACTGTTTAAACTTCCTTTATGTCGTGGCCCCTCAGGTGGATCATAATTGAGCCTAATAGACGAACGGCCTGTTGAGTATACTGTGCCGGAGTAACTAGCTATCCTTACATCACTAAAGGTTGGACACATGTACTCTACAGGACGCTCCTGATGCTCCGGATTAAAGTTGGTAGCTCCTGCTACGAATTGTGGTTATGCTCGCTTGCCCCGCTCACAGCCACATTCTCGAATCTGCCAGGTCGCGAGTGTGACTTTACCATGCCTACTATGGGGAGGAATAATCCGTAATGAAGAATCTGTAGGGTAACTAATACTCAGCCTAGTCGTTGGAACAAACCATTGGGGGGCACGAATATCTCGTGATCGTCTAGTATGGATGCCAATAGTGTTGATCAGCTGCCCCAGACAATAACAATTTATGTGGCCCTAAGGACGGTGCTAGCAGTTGCATTTGCCCGGAAATTTACTCGCGTCGGTCTTATCCGCGCATCTAGATCGAATCCTAACGTTGGTTTCGAACGACTTTTCTACAGCATGCGTTCGGTTTTCGCTTGTGCATATTTCCTGTGTATCGGTCGGAGAGCTTTCACAAAGTCCTCTACTCTGAGCCCTAAATTTCCTGTTTCAGTACGACGAATACACCGCGCAGAGCTACATTATGAGTTGGCCGCTCACCCTTCACTCTAGTGGCGAACCCACAGATCCCCTGCCGGTCGGCGGCCGAACCCACCACCGGACAGCTCAGAACAGCG");
        // write your code here
    }


    public static void countingDnaNucleotides(String dna) {

        int aCounter = 0;
        int gCounter = 0;
        int cCounter = 0;
        int tCounter = 0;

        for (char a :  dna.toCharArray()) {
            System.out.println(a);

            if (a == 'A') {
                aCounter++;
            }
            if (a == 'G') {
                gCounter++;
            }
            if (a == 'T') {
                tCounter++;
            }
            if (a == 'C') {
                cCounter++;
            }
        }
        System.out.println("Values: " + aCounter +" \n" + cCounter+" \n" +  gCounter +" \n" + tCounter);


    }
}
